version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mabd
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
